import { useEffect, useState } from 'react';
import { chooseLocation, displayPath, errorText, type NativePath } from '../bridge';
import { metadataWrite, type Bytes, type Edit, type ImageIdentity, type RecoveryEntry, type Review, type SidecarPlan, type SidecarReceipt } from '../metadataWrite';
import { useMetadataWrite } from '../state/useMetadataWrite';
import { buildMetadataEdit, type EditForm } from '../metadataWriteDraft';
import { ErrorNotice } from './Controls';

const limits={input_bytes:'16777216',existing_file_bytes:'16777216',evidence_bytes:'268435456',evidence_packets:'1024',alias_directories:'4096',alias_candidates:'256'};
function resultValue<T>(status:{operation:{result:unknown}|null}):T|undefined {const result=status.operation?.result as {kind?:string;value?:T}|null;return result?.value;}

export function MetadataEditor({catalog,identity,changed}:{catalog:string;identity:ImageIdentity;changed:()=>void}) {
  const writer=useMetadataWrite(catalog,identity);const [form,setForm]=useState<EditForm>('set');const [namespace,setNamespace]=useState('http://ns.adobe.com/xap/1.0/');const [path,setPath]=useState('Rating');const [value,setValue]=useState('');const [language,setLanguage]=useState('x-default');const [ordered,setOrdered]=useState(true);const [base,setBase]=useState<string>('');const [draft,setDraft]=useState<Edit[]>([]);const [review,setReview]=useState<Review|null>(null);const [localError,setLocalError]=useState('');
  const add=()=>{try{const edit=buildMetadataEdit(form,namespace,path,value,ordered,language);setDraft(rows=>[...rows,edit]);setReview(null);setLocalError('');}catch(e){setLocalError(errorText(e));}};
  const prepare=()=>void writer.prepare(draft,base||null).then(setReview).catch(e=>setLocalError(errorText(e)));
  const commit=()=>review&&void writer.commit(review).then(()=>{setDraft([]);setReview(null);changed();}).catch(e=>setLocalError(errorText(e)));
  return <section className="metadata-write"><h3>Edit catalog metadata</h3><p>Choose the complete retained base explicitly. Empty base starts a new packet. Catalog edits preserve retained source packets and never write an original.</p>
    {(writer.error||localError)&&<ErrorNotice message={writer.error||localError}/>}<label className="form-field">Base model ID<input value={base} inputMode="numeric" onChange={e=>{setBase(e.target.value);setReview(null);}} placeholder="Empty packet"/></label>
    <label className="form-field">Edit form<select value={form} onChange={e=>setForm(e.target.value as EditForm)}><option value="set">Set property, array item, or structure field</option><option value="remove">Remove selected subtree</option><option value="append">Append array item</option><option value="localized">Set localized language</option></select></label>
    <label className="form-field">Namespace URI<input value={namespace} onChange={e=>setNamespace(e.target.value)}/></label><label className="form-field">Property path<input value={path} onChange={e=>setPath(e.target.value)}/></label>
    {form!=='remove'&&<label className="form-field">Value<input value={value} onChange={e=>setValue(e.target.value)}/></label>}{form==='append'&&<label className="checkbox"><input type="checkbox" checked={ordered} onChange={e=>setOrdered(e.target.checked)}/>Ordered array</label>}{form==='localized'&&<label className="form-field">Language<input value={language} onChange={e=>setLanguage(e.target.value)}/></label>}
    <button disabled={writer.busy} onClick={add}>Add edit to review</button>{draft.length>0&&<><ol>{draft.map((edit,index)=><li key={index}><code>{edit.operation}</code> {edit.namespace} · {edit.path}<button onClick={()=>{setDraft(rows=>rows.filter((_,i)=>i!==index));setReview(null);}}>Remove</button></li>)}</ol><button disabled={writer.busy||!!review} onClick={prepare}>Prepare exact packet</button></>}
    {review&&<article className="metadata-review"><h4>Prepared review</h4><p>{review.edits} edits change {review.changed_fields} projected fields. Packet {review.packet.bytes} bytes.</p><code>{review.packet.blake3}</code><p>Base: {review.base_model??'empty packet'} · selected revision {review.identity.metadata_revision}</p><pre>{typeof review.issues==='string'?review.issues:review.issues.inline??`${review.issues.bytes} retained issue bytes`}</pre><button disabled={writer.busy} onClick={commit}>Commit this exact review</button><button onClick={()=>setReview(null)}>Discard review</button></article>}
    {writer.status?.operation&&!['complete','failed','canceled'].includes(writer.status.operation.phase)&&<p role="status">{writer.status.operation.stage} · {writer.status.operation.cancel_requested?'cancel requested':'running'} <button onClick={()=>void writer.cancel()}>Cancel</button></p>}
  </section>;
}

export function SidecarPanel({catalog,identity}:{catalog:string;identity:ImageIdentity}) {
  const writer=useMetadataWrite(catalog,identity);const [base,setBase]=useState('');const [destination,setDestination]=useState<{path:NativePath;display:string}|null>(null);const [plan,setPlan]=useState<SidecarPlan|null>(null);const [overwrite,setOverwrite]=useState(false);const [existingChunk,setExistingChunk]=useState<Bytes|null>(null);const [receipt,setReceipt]=useState<SidecarReceipt|null>(null);const [plans,setPlans]=useState<SidecarPlan[]>([]);const [recovery,setRecovery]=useState<{path:NativePath;display:string}|null>(null);const [entries,setEntries]=useState<RecoveryEntry[]>([]);const [evidenceObservation,setEvidenceObservation]=useState('');const [error,setError]=useState('');
  const refresh=()=>void metadataWrite(catalog,{command:'plans',args:{owner:identity.key,after:null,limit:50}},'plans').then(page=>setPlans(page.rows)).catch(e=>setError(errorText(e)));
  useEffect(refresh,[catalog,identity.image_id]);
  const choose=async(purpose:'metadata_sidecar'|'metadata_evidence'|'metadata_recovery')=>chooseLocation(purpose);
  const planNow=()=>{if(!destination||!base)return;setError('');setExistingChunk(null);void writer.start({kind:'sidecar_plan',identity,base_model:base,destination:destination.path,limits}).then(status=>{const value=resultValue<SidecarPlan>(status);if(value){setPlan(value);setReceipt(value.receipt);refresh();}}).catch(e=>setError(errorText(e)));};
  const publish=()=>{if(!plan)return;setError('');void writer.start({kind:'sidecar_apply',operation:plan.operation,authority_blake3:plan.authority_blake3,overwrite_ack:overwrite,limits}).then(status=>{const value=resultValue<SidecarReceipt>(status);if(value)setReceipt(value);refresh();}).catch(e=>setError(errorText(e)));};
  const readExisting=(offset:string)=>plan?.existing&&void metadataWrite(catalog,{command:'chunk',args:{reference:plan.existing,offset,length:4096}},'chunk').then(setExistingChunk).catch(e=>setError(errorText(e)));
  const discover=()=>recovery&&void writer.start({kind:'discover',directory:recovery.path}).then(async status=>{const value=resultValue<{token:string}>(status);if(value){const page=await metadataWrite(catalog,{command:'recovery_entries',args:{token:value.token,after:null,limit:50}},'recovery_entries');setEntries(page.rows);}}).catch(e=>setError(errorText(e)));
  const recover=(entry:RecoveryEntry,restore:boolean)=>{if(!entry.operation)return;const saved=plans.find(value=>value.operation===entry.operation);if(!saved)return setError('Load the matching saved catalog plan before recovery.');void writer.start(restore?{kind:'sidecar_restore',operation:saved.operation,authority_blake3:saved.authority_blake3,recovery_directory:entry.directory,limits}:{kind:'sidecar_recover',operation:saved.operation,authority_blake3:saved.authority_blake3,recovery_directory:entry.directory,may_publish_ack:true,limits}).then(status=>{const value=resultValue<SidecarReceipt>(status);if(value)setReceipt(value);refresh();}).catch(e=>setError(errorText(e)));};
  const evidence=async()=>{const selected=await choose('metadata_evidence');if(selected&&evidenceObservation)await writer.start({kind:'evidence_export',identity,observation:evidenceObservation,destination:selected.path,limits});};
  return <section className="metadata-write"><h3>Write XMP sidecar</h3><p>Publication writes only the selected <code>.xmp</code> path. Existing bytes are hashed and captured for recovery; originals remain unchanged.</p>{(writer.error||error)&&<ErrorNotice message={writer.error||error}/>}<label className="form-field">Complete base model ID<input value={base} inputMode="numeric" onChange={e=>{setBase(e.target.value);setPlan(null);setExistingChunk(null);}}/></label><button onClick={()=>void choose('metadata_sidecar').then(value=>{if(value){setDestination(value);setPlan(null);setExistingChunk(null);}})}>Choose exact sidecar path…</button>{destination&&<p>{destination.display}</p>}<button disabled={!base||!destination||writer.busy} onClick={planNow}>Prepare sidecar plan</button>
    {plan&&<article className="metadata-review"><h4>Exact destination review</h4><p>{displayPath(plan.destination)}</p><p>New packet: {plan.payload_bytes} bytes · BLAKE3 {plan.payload_digest}</p>{plan.expected?<><p>Existing snapshot: {plan.expected.bytes} bytes within the selected {plan.max_existing_bytes} byte limit · BLAKE3 {plan.expected.digest}</p><p>Modified nanoseconds: {plan.expected.modified_ns} · file identity {plan.expected.identity[0]}:{plan.expected.identity[1]}</p>{plan.existing&&<><button onClick={()=>readExisting('0')}>Read exact existing bytes</button>{existingChunk&&<article><p>Verified bytes {existingChunk.offset}–{String(BigInt(existingChunk.offset)+BigInt(existingChunk.bytes.length))} of {existingChunk.total}</p><pre>{existingChunk.bytes.map(byte=>byte.toString(16).padStart(2,'0')).join(' ')}</pre>{existingChunk.next&&<button onClick={()=>readExisting(existingChunk.next!)}>Read next bytes</button>}</article>}</>}<label className="checkbox"><input type="checkbox" checked={overwrite} onChange={e=>setOverwrite(e.target.checked)}/>I reviewed and approve replacement of this exact byte count, digest, timestamp, and file identity</label></>:<p>Destination was absent when planned.</p>}<button disabled={!!plan.expected&&!overwrite||writer.busy} onClick={publish}>Publish reviewed sidecar</button></article>}
    {receipt&&<article><h4>{receipt.state}</h4><p>{receipt.detail}</p><p>Recovery evidence: {displayPath(receipt.recovery_directory)}</p></article>}
    <details><summary>Saved plans</summary><button onClick={refresh}>Refresh saved plans</button>{plans.map(value=><article key={value.operation}><p>{value.operation}</p><p>{displayPath(value.destination)} · {value.payload_bytes} bytes</p><button onClick={()=>{setPlan(value);setReceipt(value.receipt);setOverwrite(false);setExistingChunk(null);}}>Review this plan</button></article>)}</details>
    <details><summary>Recovery directories</summary><p>Recover may publish the staged sidecar when catalog authority is current. Restore only attempts to return a captured destination and never publishes staged metadata.</p><button onClick={()=>void choose('metadata_recovery').then(setRecovery)}>Choose recovery parent…</button>{recovery&&<button onClick={discover}>Inspect bounded entries</button>}{entries.map((entry,index)=><article key={index}><p>{entry.kind} · {entry.operation??'foreign or incomplete operation'}</p><p>{entry.detail}</p>{entry.operation&&<><button onClick={()=>recover(entry,false)}>Recover with publish acknowledgement</button><button onClick={()=>recover(entry,true)}>Restore captured destination only</button></>}</article>)}</details>
    <details><summary>Export exact retained packet evidence</summary><label className="form-field">Observation ID<input value={evidenceObservation} inputMode="numeric" onChange={e=>setEvidenceObservation(e.target.value)}/></label><button disabled={!evidenceObservation||writer.busy} onClick={()=>void evidence().catch(e=>setError(errorText(e)))}>Create new JSON evidence file…</button></details>
  </section>;
}
