import { describe,expect,it,vi } from 'vitest';
import { decimal,encodeInput,inputChunk,utf8Length,field,inspectionFormScope,invalidatesInspectionSelection,reviewedCaptureRevision,sameInspectionDescriptor,selectionDocument,nextQuery,inputObserved,type InspectionDescriptor } from './lightroomWorkflow';
import type { Action } from './lightroom';
import { parseLosslessJson } from './lightroomJson';
const parse=(raw:string)=>parseLosslessJson(raw,{bytes:10000,nodes:1000,depth:20});
describe('Lightroom inspection authority',()=>{
 const status=(workbench:string,generation:string,operation:string)=>({workbench,generation,operation});
 it('preserves exact decimal identities and rejects coercion',()=>{expect(decimal('9007199254740993','ID')).toBe('9007199254740993');for(const v of ['01','1e2','1.0','-1','18446744073709551616'])expect(()=>decimal(v,'ID')).toThrow();});
 it('chunks UTF8 exactly without splitting scalar boundaries',()=>{const text='é'.repeat(3000)+'🌲abc',bytes=encodeInput(text);let offset='0',joined='';while(BigInt(offset)<BigInt(bytes.length)){const part=inputChunk(bytes,offset,'4096');joined+=part.fragment;offset=part.next;}expect(joined).toBe(text);expect(()=>inputChunk(encodeInput('🌲'),'1','4')).toThrow();expect(()=>utf8Length('\ud800')).toThrow();});
 it('preserves U+FEFF at a chunk boundary inside exact JSON',()=>{const raw='{"v":"'+'a'.repeat(4090)+'\ufeffend"}',bytes=encodeInput(raw);let at='0',joined='';while(BigInt(at)<BigInt(bytes.length)){const part=inputChunk(bytes,at,'4096');expect(BigInt(utf8Length(part.fragment))).toBe(BigInt(part.next)-BigInt(at));joined+=part.fragment;at=part.next;}expect(joined).toBe(raw);});
 it('encodes a maximum-size document once and never rescans prefixes during chunking',()=>{const encode=vi.spyOn(TextEncoder.prototype,'encode');try{const bytes=encodeInput('a'.repeat(16777216));expect(encode).toHaveBeenCalledTimes(1);let offset='0',count=0;while(BigInt(offset)<BigInt(bytes.length)){const part=inputChunk(bytes,offset,'16384');expect(part.fragment.length).toBe(16384);offset=part.next;count++;}expect(count).toBe(1024);expect(encode).toHaveBeenCalledTimes(1);}finally{encode.mockRestore();}});
 it('retains duplicate fields but rejects ambiguous control extraction',()=>expect(()=>field(parse('{"id":1,"id":2}'),'id')).toThrow());
 it('requires all-family decisions and preserves exact evidence',()=>{const rows=[{id:'f',evidence:'digest',members:[{revision:'9007199254740993',source:parse('{}'),details:parse('{}')}],details:parse('{}')}];expect(()=>selectionDocument({encoding:'UnixBytes',units:[47]},rows,{})).toThrow();expect(selectionDocument({encoding:'UnixBytes',units:[47]},rows,{f:'9007199254740993'})).toContain('"revision":"9007199254740993"');});
 it('targets the pinned database while preserving opaque native directory units',()=>{
  const rows=[{id:'f',evidence:'digest',members:[],details:parse('{}')}];
  const cases:[import('./bridge').NativePath,number[]][]=[
   [{encoding:'UnixBytes',units:[47,255]},[47,255,47]],
   [{encoding:'UnixBytes',units:[47]},[47]],
   [{encoding:'WindowsWide',units:[67,58,92,0xd800]},[67,58,92,0xd800,92]],
   [{encoding:'WindowsWide',units:[67,58,92]},[67,58,92]],
   [{encoding:'WindowsWide',units:[67,58,47]},[67,58,47]],
  ];
  for(const [root,prefix] of cases){const before=[...root.units];const document=JSON.parse(selectionDocument(root,rows,{f:'exclude'}));expect(document.inspection).toEqual({encoding:root.encoding,units:[...prefix,...Array.from('inspection.sqlite3',c=>c.charCodeAt(0))]});expect(root.units).toEqual(before);}
 });
 it('uses authoritative cursors rather than row count or draft',()=>{expect(nextQuery({kind:'Rows',revision:'r',table:null,after:'0',limit:'20'},parse('{"rows":[],"next":"9007199254740993"}'))).toMatchObject({after:'9007199254740993'});expect(nextQuery({kind:'PathCollisions',left:'l',right:'r',after_left:'0',after_right:'0',limit:'20'},parse('{"next":["9007199254740993","4"]}'))).toMatchObject({after_left:'9007199254740993',after_right:'4'});});
 it('preserves object-shaped global ID cursors independently from collision tuples',()=>{expect(nextQuery({kind:'GlobalIdConflicts',left:'a',right:'b',after_left:'',after_right:'',limit:'20'},parse('{"next":{"left":"9007199254740993","right":"provider:opaque/id"},"rows":[]}'))).toEqual({kind:'GlobalIdConflicts',left:'a',right:'b',after_left:'9007199254740993',after_right:'provider:opaque/id',limit:'20'});});
 it('does not mistake unchanged upload progress for append settlement',()=>{const status={input:'i',received_bytes:'0'} as never;expect(inputObserved({kind:'append',input:'i',next:'4096'},status)).toBe(false);expect(inputObserved({kind:'discard',input:'i'},null)).toBe(true);});
 it('retains form scope across generation rotation but resets for a new workbench',()=>{expect(inspectionFormScope(status('w','1','old'))).toBe(inspectionFormScope(status('w','2','new')));expect(inspectionFormScope(status('next','1','new'))).not.toBe(inspectionFormScope(status('w','2','new')));});
 it('fills the registered AddCapture revision after rotation and rejects stale results',()=>{const descriptor:InspectionDescriptor={workbench:'w',operation:'add',action:{kind:'AddCapture',directory:{encoding:'UnixBytes',units:[47]}}};const node=parse('{"revision":"registered"}');expect(reviewedCaptureRevision(descriptor,status('w','2','add'),node)).toBe('registered');expect(reviewedCaptureRevision(descriptor,status('w','2','later'),node)).toBeNull();expect(reviewedCaptureRevision(descriptor,status('next','2','add'),node)).toBeNull();});
 it('rejects every reviewed result descriptor from a stale operation or workbench',()=>{const descriptor:InspectionDescriptor={workbench:'w',operation:'read',query:{kind:'Families'}};expect(sameInspectionDescriptor(descriptor,status('w','2','read'))).toBe(true);expect(sameInspectionDescriptor(descriptor,status('w','2','later'))).toBe(false);expect(sameInspectionDescriptor(descriptor,status('next','2','read'))).toBe(false);});
 it('invalidates selection authority for every plan write but not capture evidence',()=>{const writes:Action[]=[{kind:'RegisterInventory',input:'i'},{kind:'AddCapture',directory:{encoding:'UnixBytes',units:[47]}},{kind:'Resume',revision:'r',max_rows:'1'},{kind:'InspectOriginals',revision:'r',limit:'1',inspection:'Packets'},{kind:'AssignFamily',revision:'r',family:'f',reason:'why'},{kind:'Choose',family:'f',revision:'r',expected_evidence:'e',reason:'why'},{kind:'ReleaseReview'}];for(const action of writes)expect(invalidatesInspectionSelection(action)).toBe(true);expect(invalidatesInspectionSelection({kind:'Capture',source:{encoding:'UnixBytes',units:[47]},output:{encoding:'UnixBytes',units:[47]},include_auxiliary:false,closed_application_evidence:null,limits:{max_files:'1',max_depth:'1',max_file_bytes:'1',max_total_bytes:'1',max_cell_bytes:'1'}})).toBe(false);});
});
