import { describe,expect,it,vi } from 'vitest';
import { decimal,encodeInput,inputChunk,utf8Length,field,selectionDocument,nextQuery,inputObserved } from './lightroomWorkflow';
import { parseLosslessJson } from './lightroomJson';
const parse=(raw:string)=>parseLosslessJson(raw,{bytes:10000,nodes:1000,depth:20});
describe('Lightroom inspection authority',()=>{
 it('preserves exact decimal identities and rejects coercion',()=>{expect(decimal('9007199254740993','ID')).toBe('9007199254740993');for(const v of ['01','1e2','1.0','-1','18446744073709551616'])expect(()=>decimal(v,'ID')).toThrow();});
 it('chunks UTF8 exactly without splitting scalar boundaries',()=>{const text='é'.repeat(3000)+'🌲abc',bytes=encodeInput(text);let offset='0',joined='';while(BigInt(offset)<BigInt(bytes.length)){const part=inputChunk(bytes,offset,'4096');joined+=part.fragment;offset=part.next;}expect(joined).toBe(text);expect(()=>inputChunk(encodeInput('🌲'),'1','4')).toThrow();expect(()=>utf8Length('\ud800')).toThrow();});
 it('preserves U+FEFF at a chunk boundary inside exact JSON',()=>{const raw='{"v":"'+'a'.repeat(4090)+'\ufeffend"}',bytes=encodeInput(raw);let at='0',joined='';while(BigInt(at)<BigInt(bytes.length)){const part=inputChunk(bytes,at,'4096');expect(BigInt(utf8Length(part.fragment))).toBe(BigInt(part.next)-BigInt(at));joined+=part.fragment;at=part.next;}expect(joined).toBe(raw);});
 it('encodes a maximum-size document once and never rescans prefixes during chunking',()=>{const encode=vi.spyOn(TextEncoder.prototype,'encode');try{const bytes=encodeInput('a'.repeat(16777216));expect(encode).toHaveBeenCalledTimes(1);let offset='0',count=0;while(BigInt(offset)<BigInt(bytes.length)){const part=inputChunk(bytes,offset,'16384');expect(part.fragment.length).toBe(16384);offset=part.next;count++;}expect(count).toBe(1024);expect(encode).toHaveBeenCalledTimes(1);}finally{encode.mockRestore();}});
 it('retains duplicate fields but rejects ambiguous control extraction',()=>expect(()=>field(parse('{"id":1,"id":2}'),'id')).toThrow());
 it('requires all-family decisions and preserves exact evidence',()=>{const rows=[{id:'f',evidence:'digest',members:[{revision:'9007199254740993',source:parse('{}'),details:parse('{}')}],details:parse('{}')}];expect(()=>selectionDocument({encoding:'UnixBytes',units:[47]},rows,{})).toThrow();expect(selectionDocument({encoding:'UnixBytes',units:[47]},rows,{f:'9007199254740993'})).toContain('"revision":"9007199254740993"');});
 it('uses authoritative cursors rather than row count or draft',()=>{expect(nextQuery({kind:'Rows',revision:'r',table:null,after:'0',limit:'20'},parse('{"rows":[],"next":"9007199254740993"}'))).toMatchObject({after:'9007199254740993'});expect(nextQuery({kind:'PathCollisions',left:'l',right:'r',after_left:'0',after_right:'0',limit:'20'},parse('{"next":["9007199254740993","4"]}'))).toMatchObject({after_left:'9007199254740993',after_right:'4'});});
 it('preserves object-shaped global ID cursors independently from collision tuples',()=>{expect(nextQuery({kind:'GlobalIdConflicts',left:'a',right:'b',after_left:'',after_right:'',limit:'20'},parse('{"next":{"left":"9007199254740993","right":"provider:opaque/id"},"rows":[]}'))).toEqual({kind:'GlobalIdConflicts',left:'a',right:'b',after_left:'9007199254740993',after_right:'provider:opaque/id',limit:'20'});});
 it('does not mistake unchanged upload progress for append settlement',()=>{const status={input:'i',received_bytes:'0'} as never;expect(inputObserved({kind:'append',input:'i',next:'4096'},status)).toBe(false);expect(inputObserved({kind:'discard',input:'i'},null)).toBe(true);});
});
